(define (problem prob1)
	(:domain supply-chain)
	(:objects
		brand1 brand2 brand3 brand4 - brand
		sugar-cane - raw-cane
		truck1 truck2 - truck
		depot1 depot2 depot3 - depot
		mill1 mill2 mill3 - mill
		crane1 crane2 crane3 - crane
	)
	(:init
		(current-process mill1 brand1)
		(= (max-changing mill2) 2.0)
		(= (in-storage depot1 brand3) 0.0)
		(= (inventory-cost) 0.0)
		(= (labour-cost) 0.0)
		(= (in-storage mill2 brand1) 0.0)
		(= (max-changing mill3) 2.0)
		(connected mill3 depot1)
		(change-process brand4 brand3)
		(connected depot3 depot1)
		(= (truck-cap truck2) 6.0)
		(produce mill2 brand3)
		(at-location crane1 mill1)
		(= (mill-cost) 0.0)
		(at-location crane3 mill3)
		(available mill1)
		(at-location truck2 depot2)
		(= (has-resource sugar-cane mill2) 10.0)
		(connected mill1 mill3)
		(change-process brand1 brand3)
		(= (in-storage mill3 brand4) 2.0)
		(change-process brand3 brand4)
		(= (max-produce mill3) 10.0)
		(change-process brand2 brand4)
		(= (in-storage mill2 brand2) 0.0)
		(= (in-truck-sugar brand4 truck2) 0.0)
		(connected depot1 mill1)
		(= (in-storage depot3 brand1) 0.0)
		(= (has-resource sugar-cane mill3) 10.0)
		(= (in-storage mill1 brand3) 0.0)
		(= (in-storage depot1 brand4) 0.0)
		(= (capacity crane3) 5.0)
		(= (in-storage mill1 brand1) 0.0)
		(= (in-storage mill2 brand3) 0.0)
		(= (in-storage mill3 brand2) 0.0)
		(produce mill2 brand4)
		(= (in-truck-sugar brand2 truck2) 0.0)
		(= (truck-cap truck1) 10.0)
		(produce mill2 brand2)
		(= (in-storage depot1 brand1) 0.0)
		(produce mill1 brand3)
		(connected depot2 depot1)
		(connected mill3 mill1)
		(= (in-storage depot3 brand4) 0.0)
		(= (in-truck-sugar brand3 truck1) 0.0)
		(ready-crane crane1)
		(connected depot3 mill3)
		(change-process brand4 brand2)
		(= (in-storage depot2 brand1) 0.0)
		(= (capacity crane2) 5.0)
		(connected mill1 depot1)
		(= (handling-cost) 0.0)
		(current-process mill2 brand3)
		(= (in-storage depot3 brand3) 0.0)
		(= (max-changing mill1) 2.0)
		(connected depot3 mill2)
		(change-process brand2 brand1)
		(= (unharvest-field) 3.0)
		(= (has-resource sugar-cane mill1) 0.0)
		(connected mill1 mill2)
	)
	(:goal
			(and
				(>= (in-storage depot1 brand4) 4.0)
				(>= (in-storage depot2 brand4) 4.0)
			)
	)
)