(define (problem prob1)
	(:domain supply-chain)
	(:objects
		brand1 brand2 brand3 brand4 - brand
		sugar-cane - raw-cane
		truck1 truck2 - truck
		depot1 depot2 depot3 - depot
		mill1 mill2 mill3 - mill
		crane1 crane2 crane3 - crane
	)
	(:init
		(connected mill1 depot2)
		(= (in-storage depot3 brand1) 0.0)
		(connected depot3 depot2)
		(current-process mill2 brand3)
		(connected depot3 mill2)
		(= (in-storage depot1 brand2) 0.0)
		(= (in-storage mill1 brand3) 0.0)
		(at-location crane2 mill2)
		(= (in-truck-sugar brand4 truck1) 0.0)
		(= (cost-process mill2) 3.0)
		(= (labour-cost) 0.0)
		(available mill1)
		(change-process brand1 brand3)
		(= (has-resource sugar-cane mill1) 0.0)
		(connected mill1 mill3)
		(produce mill1 brand1)
		(connected mill2 depot2)
		(change-process brand4 brand1)
		(current-process mill1 brand1)
		(connected depot2 depot1)
		(connected mill1 depot1)
		(connected depot1 depot2)
		(connected mill3 depot2)
		(produce mill2 brand2)
		(= (max-produce mill1) 5.0)
		(= (truck-cap truck2) 6.0)
		(produce mill2 brand4)
		(change-process brand3 brand2)
		(= (max-service-time crane1) 10.0)
		(= (in-storage depot3 brand4) 0.0)
		(connected depot1 mill3)
		(connected depot1 mill1)
		(= (capacity crane1) 5.0)
		(at-location truck1 depot1)
		(= (max-changing mill2) 2.0)
		(= (mill-cost) 0.0)
		(change-process brand2 brand4)
		(connected depot3 mill1)
		(= (max-produce mill3) 10.0)
		(= (in-storage depot2 brand3) 0.0)
		(connected mill2 mill1)
		(= (has-resource sugar-cane mill3) 10.0)
		(ready-crane crane2)
		(= (max-service-time crane2) 15.0)
		(produce mill3 brand1)
		(= (in-storage mill2 brand3) 0.0)
		(change-process brand1 brand4)
		(= (capacity crane2) 5.0)
		(= (cost-process mill3) 6.0)
		(= (capacity crane3) 5.0)
		(connected depot3 mill3)
		(produce mill1 brand4)
		(change-process brand2 brand1)
		(change-process brand1 brand2)
		(change-process brand4 brand3)
		(= (in-truck-sugar brand1 truck1) 0.0)
		(= (service-time crane1) 10.0)
		(= (in-truck-sugar brand3 truck1) 0.0)
		(connected mill2 mill3)
		(= (max-changing mill3) 2.0)
	)
	(:goal
			(and
				(>= (in-storage depot1 brand4) 4.0)
				(>= (in-storage depot2 brand4) 4.0)
			)
	)
)