#Here are things that probably never change so they will be cached
FROM 775013819650.dkr.ecr.eu-south-1.amazonaws.com/patty:stable

WORKDIR /
COPY /benchmarks/planners/icr /var/icr
ENV PATH /var/icr/:${PATH}
RUN chmod +x /var/icr/icr

WORKDIR /project
RUN rm -rf \*
RUN pip install prettytable scipy

# Copying

COPY . .

#Authorizations
RUN chmod +x exes/*

#Execution
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "patty", "./exes/run-icr.sh"]
