#! /bin/bash

DOMAIN=$1
PROBLEM=$2
PLAN=$3

./patty.sif \
 -o $DOMAIN \
 -f $PROBLEM \
 -sp $PLAN \
 -pp \
 -s jair \
 --pattern enhanced \
 --quality none \
 --jair-search-strategy G \
 --jair-goal-function n \
 --jair-pattern-g e \
 --jair-pattern-h i