(define (problem mprime-x-2)
	(:domain mystery-prime-typed)
	(:objects
		beef onion tuna flounder cherry muffin ham - food
		satiety stimulation curiosity entertainment - pleasure
		anger depression prostatitis grief abrasion loneliness dread angina boils laceration sciatica hangover anxiety jealousy jealousy-2 depression-1 grief-7 dread-8 prostatitis-3 boils-4 - pain
	)
	(:init
		(eats flounder tuna)
		(craves anger beef)
		(= (harmony satiety) 1.0)
		(= (locale ham) 4.0)
		(craves dread-8 ham)
		(craves stimulation flounder)
		(eats beef cherry)
		(= (locale flounder) 2.0)
		(craves depression beef)
		(eats ham muffin)
		(eats muffin tuna)
		(craves jealousy flounder)
		(eats tuna muffin)
		(= (harmony curiosity) 2.0)
		(eats cherry onion)
		(eats onion beef)
		(craves loneliness onion)
		(eats tuna ham)
		(= (harmony stimulation) 2.0)
		(craves prostatitis-3 ham)
		(eats beef onion)
		(craves grief-7 ham)
		(= (locale beef) 4.0)
		(eats cherry flounder)
		(craves sciatica tuna)
		(= (locale onion) 3.0)
		(craves prostatitis beef)
	)
	(:goal
			(and
				(craves grief-7 beef)
				(craves depression-1 beef)
			)
	)
)