(define (problem mprime-x-2)
	(:domain mystery-prime-typed)
	(:objects
		beef onion tuna flounder cherry muffin ham - food
		satiety stimulation curiosity entertainment - pleasure
		anger depression prostatitis grief abrasion loneliness dread angina boils laceration sciatica hangover anxiety jealousy jealousy-2 depression-1 grief-7 dread-8 prostatitis-3 boils-4 - pain
	)
	(:init
		(eats flounder tuna)
		(craves depression beef)
		(craves angina onion)
		(craves entertainment ham)
		(eats tuna ham)
		(craves jealousy flounder)
		(craves stimulation flounder)
		(craves satiety onion)
		(= (locale onion) 3.0)
		(= (locale ham) 4.0)
		(craves dread-8 ham)
		(craves boils-4 ham)
		(craves grief beef)
		(eats flounder cherry)
		(= (harmony entertainment) 3.0)
		(craves boils tuna)
		(= (locale beef) 4.0)
		(eats cherry beef)
		(craves depression-1 muffin)
		(eats ham muffin)
		(craves hangover tuna)
		(eats tuna flounder)
		(= (locale flounder) 2.0)
		(eats tuna beef)
		(eats tuna muffin)
		(eats muffin ham)
		(eats beef cherry)
	)
	(:goal
			(and
				(craves grief-7 beef)
				(craves depression-1 beef)
			)
	)
)