(define (problem prob_9_5_4)
(:domain bottles)
	(:objects
		 l1 l2 l3 l4 l5 - bottleleft
		 r1 r2 r3 r4 - bottleright
	)
	(:init
		(= (litres l1) 4)
		(= (litres l2) 4)
		(= (litres l3) 12)
		(= (litres l4) 3)
		(= (litres l5) 4)
		(= (litres r1) 0)
		(= (litres r2) 0)
		(= (litres r3) 0)
		(= (litres r4) 0)
		(capped l1)
		(capped l2)
		(capped l3)
		(capped l4)
		(capped l5)
		(capped r1)
		(capped r2)
		(capped r3)
		(capped r4)
	)
	(:goal
		(and
			(= (litres r1) 4)
			(= (litres r2) 3)
			(= (litres r3) 6)
			(= (litres r4) 14)
		)
	)
)