(define (problem prob_9_5_4)
(:domain bottles)
	(:objects
		 l1 l2 l3 l4 l5 - bottleleft
		 r1 r2 r3 r4 - bottleright
	)
	(:init
		(= (litres l1) 9)
		(= (litres l2) 23)
		(= (litres l3) 5)
		(= (litres l4) 7)
		(= (litres l5) 1)
		(= (litres r1) 0)
		(= (litres r2) 0)
		(= (litres r3) 0)
		(= (litres r4) 0)
		(capped l1)
		(capped l2)
		(capped l3)
		(capped l4)
		(capped l5)
		(capped r1)
		(capped r2)
		(capped r3)
		(capped r4)
	)
	(:goal
		(and
			(= (litres r1) 27)
			(= (litres r2) 5)
			(= (litres r3) 5)
			(= (litres r4) 8)
		)
	)
)