(define (problem prob_9_3_6)
(:domain bottles)
	(:objects
		 l1 l2 l3 - bottleleft
		 r1 r2 r3 r4 r5 r6 - bottleright
	)
	(:init
		(= (litres l1) 8)
		(= (litres l2) 2)
		(= (litres l3) 17)
		(= (litres r1) 0)
		(= (litres r2) 0)
		(= (litres r3) 0)
		(= (litres r4) 0)
		(= (litres r5) 0)
		(= (litres r6) 0)
		(capped l1)
		(capped l2)
		(capped l3)
		(capped r1)
		(capped r2)
		(capped r3)
		(capped r4)
		(capped r5)
		(capped r6)
	)
	(:goal
		(and
			(= (litres r1) 4)
			(= (litres r2) 1)
			(= (litres r3) 1)
			(= (litres r4) 14)
			(= (litres r5) 4)
			(= (litres r6) 3)
		)
	)
)