(define (problem prob_9_1_8)
(:domain bottles)
	(:objects
		 l1 - bottleleft
		 r1 r2 r3 r4 r5 r6 r7 r8 - bottleright
	)
	(:init
		(= (litres l1) 45)
		(= (litres r1) 0)
		(= (litres r2) 0)
		(= (litres r3) 0)
		(= (litres r4) 0)
		(= (litres r5) 0)
		(= (litres r6) 0)
		(= (litres r7) 0)
		(= (litres r8) 0)
		(capped l1)
		(capped r1)
		(capped r2)
		(capped r3)
		(capped r4)
		(capped r5)
		(capped r6)
		(capped r7)
		(capped r8)
	)
	(:goal
		(and
			(= (litres r1) 4)
			(= (litres r2) 2)
			(= (litres r3) 21)
			(= (litres r4) 3)
			(= (litres r5) 4)
			(= (litres r6) 1)
			(= (litres r7) 5)
			(= (litres r8) 5)
		)
	)
)