(define (problem pb01)
            (:domain counters)
            (:objects sea atomic bomb earth stone grass swamp tsunami atmosphere sun archipelago wall grenade hurricane dust rain earthquake fire garden fireworks electricity mountain range lava gunpowder air fog water wave geyser sandstorm cactus explosion isle wind steel ocean dew salt diamond sound rust metal ash flower algae tobacco beach mud horizon moss eruption bullet obsidian plant mountain coal sand clay flood cloud brick sky cotton storm blade granite seaweed steam pressure glass ivy river energy volcano - element)
            (:init
                (have water)
                (have earth)
                (have fire)
                (have air)
                (combination air air pressure) (combination air fire energy) (combination air earth dust) (combination earth fire lava) (combination air water rain) (combination earth water mud) (combination fire water steam) (combination water water sea) (combination air energy wind) (combination air lava stone) (combination air pressure atmosphere) (combination air steam cloud) (combination earth energy earthquake) (combination dust fire gunpowder) (combination fire sea salt) (combination earth lava volcano) (combination lava pressure granite) (combination lava water obsidian) (combination fire mud brick) (combination earth rain plant) (combination rain rain flood) (combination sea sea ocean) (combination steam earth geyser) (combination air cloud sky) (combination air stone sand) (combination brick brick wall) (combination cloud earth fog) (combination earth earthquake mountain) (combination cloud energy storm) (combination fire stone metal) (combination fire gunpowder explosion) (combination mud plant swamp) (combination earthquake ocean tsunami) (combination ocean plant algae) (combination ocean volcano isle) (combination ocean wind wave) (combination cloud plant cotton) (combination earth plant grass) (combination fire plant tobacco) (combination ocean plant seaweed) (combination plant plant garden) (combination plant stone moss) (combination plant pressure coal) (combination energy volcano ash) (combination air steam cloud) (combination energy volcano eruption) (combination energy wind hurricane) (combination air metal rust) (combination air wave sound) (combination energy explosion atomic bomb) (combination explosion metal grenade) (combination explosion sky fireworks) (combination fire sand glass) (combination fire sky sun) (combination fog grass dew) (combination gunpowder metal bullet) (combination isle isle archipelago) (combination coal metal steel) (combination energy metal electricity) (combination metal stone blade) (combination mountain mountain mountain range) (combination mountain water river) (combination ocean sand beach) (combination ocean sky horizon) (combination garden plant flower) (combination plant wall ivy) (combination coal pressure diamond) (combination energy sand sandstorm) (combination mud sand clay) (combination plant sand cactus)
            )
            (:goal
                (and  (have atomic bomb))
            )
            )

                    