(define (problem roverprob3726)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 - rover
		rover0store rover1store - store
		waypoint0 waypoint1 waypoint2 waypoint3 - waypoint
		camera0 camera1 - camera
		objective0 objective1 - objective
	)
	(:init
		(in_sun waypoint0)
		(visible waypoint3 waypoint1)
		(in rover0 waypoint1)
		(calibration_target camera1 objective0)
		(can_traverse rover1 waypoint3 waypoint0)
		(can_traverse rover1 waypoint1 waypoint0)
		(visible_from objective0 waypoint1)
		(at_lander general waypoint0)
		(equipped_for_imaging rover1)
		(visible waypoint0 waypoint2)
		(visible waypoint2 waypoint3)
		(visible waypoint1 waypoint0)
		(at_soil_sample waypoint2)
		(can_traverse rover0 waypoint1 waypoint0)
		(visible waypoint1 waypoint2)
		(equipped_for_imaging rover0)
		(supports camera1 high_res)
		(can_traverse rover1 waypoint3 waypoint2)
		(visible_from objective1 waypoint1)
		(in rover1 waypoint3)
		(= (energy rover1) 50.0)
		(at_rock_sample waypoint0)
		(visible waypoint3 waypoint0)
		(available rover0)
		(on_board camera1 rover1)
		(in_sun waypoint1)
		(at_rock_sample waypoint2)
		(visible waypoint0 waypoint1)
		(supports camera1 low_res)
		(channel_free general)
		(= (recharges) 0.0)
		(supports camera1 colour)
		(calibration_target camera0 objective1)
		(available rover1)
		(equipped_for_rock_analysis rover1)
		(at_rock_sample waypoint1)
		(can_traverse rover1 waypoint2 waypoint3)
		(visible waypoint0 waypoint3)
		(visible_from objective0 waypoint0)
		(empty rover0store)
		(equipped_for_rock_analysis rover0)
		(can_traverse rover0 waypoint0 waypoint1)
		(can_traverse rover1 waypoint0 waypoint3)
		(visible waypoint3 waypoint2)
	)
	(:goal
			(and
				(communicated_soil_data waypoint2)
				(communicated_rock_data waypoint0)
				(communicated_image_data objective0 colour)
			)
	)
)