(define (problem prob1)
	(:domain supply-chain)
	(:objects
		brand1 brand2 brand3 brand4 - brand
		sugar-cane - raw-cane
		truck1 truck2 - truck
		depot1 depot2 depot3 - depot
		mill1 mill2 - mill
		crane1 crane2 crane3 - crane
	)
	(:init
		(= (in-truck-sugar brand4 truck2) 0.0)
		(at-location truck1 depot1)
		(connected depot2 depot3)
		(= (max-produce mill1) 5.0)
		(connected depot2 mill2)
		(= (in-truck-sugar brand3 truck2) 0.0)
		(= (max-service-time crane1) 10.0)
		(produce mill2 brand3)
		(= (service-time crane2) 15.0)
		(change-process brand1 brand3)
		(at-location crane1 mill1)
		(= (cost-process mill1) 1.0)
		(= (in-storage depot1 brand2) 0.0)
		(= (in-storage depot2 brand4) 0.0)
		(change-process brand2 brand3)
		(= (service-time crane3) 10.0)
		(= (max-changing mill2) 2.0)
		(= (in-storage depot3 brand1) 0.0)
		(connected mill2 depot1)
		(= (in-truck-sugar brand2 truck2) 0.0)
		(connected depot3 mill1)
		(at-location crane2 mill2)
		(= (in-truck-sugar brand3 truck1) 0.0)
		(= (in-storage depot3 brand2) 0.0)
		(= (capacity crane2) 5.0)
		(change-process brand3 brand2)
		(produce mill1 brand4)
		(connected depot2 mill1)
		(current-process mill1 brand1)
		(change-process brand2 brand4)
		(connected mill2 depot2)
		(available mill2)
		(connected mill1 depot2)
		(= (inventory-cost) 0.0)
		(current-process mill2 brand3)
		(= (in-storage depot3 brand3) 0.0)
		(= (service-time crane1) 10.0)
		(= (in-storage depot3 brand4) 0.0)
		(= (in-storage depot1 brand3) 0.0)
		(connected mill1 depot3)
		(connected depot2 depot1)
		(change-process brand3 brand1)
		(connected mill1 mill2)
		(connected depot1 depot2)
		(connected mill1 depot1)
		(= (in-truck-sugar brand4 truck1) 0.0)
		(change-process brand4 brand2)
	)
	(:goal
			(and
				(>= (in-storage depot1 brand3) 3.0)
			)
	)
)