(define (problem prob1)
	(:domain supply-chain)
	(:objects
		brand1 brand2 brand3 brand4 - brand
		sugar-cane - raw-cane
		truck1 truck2 - truck
		depot1 depot2 depot3 - depot
		mill1 mill2 - mill
		crane1 crane2 crane3 - crane
	)
	(:init
		(connected mill2 depot1)
		(= (in-storage mill2 brand3) 0.0)
		(connected depot3 depot2)
		(= (handling-cost) 0.0)
		(= (in-truck-sugar brand1 truck2) 0.0)
		(= (inventory-cost) 0.0)
		(= (has-resource sugar-cane mill2) 5.0)
		(current-process mill1 brand1)
		(current-process mill2 brand3)
		(= (truck-cap truck2) 6.0)
		(available mill1)
		(= (in-storage depot2 brand2) 0.0)
		(= (in-storage depot1 brand1) 0.0)
		(connected mill2 depot3)
		(connected depot1 depot3)
		(connected depot3 mill2)
		(= (truck-cap truck1) 10.0)
		(ready-crane crane2)
		(= (in-storage mill1 brand1) 0.0)
		(= (cost-process mill2) 3.0)
		(= (in-truck-sugar brand3 truck1) 0.0)
		(= (max-service-time crane1) 10.0)
		(at-location truck1 depot1)
		(= (in-storage mill2 brand1) 0.0)
		(= (service-time crane2) 15.0)
		(= (max-produce mill2) 8.0)
		(= (in-storage depot3 brand2) 0.0)
		(= (in-storage depot2 brand1) 0.0)
		(= (cost-process mill1) 1.0)
		(= (capacity crane2) 5.0)
		(ready-crane crane1)
		(change-process brand1 brand2)
		(= (in-storage mill2 brand2) 0.0)
		(= (in-storage depot1 brand4) 0.0)
		(= (max-changing mill1) 2.0)
		(= (capacity crane1) 3.0)
		(= (unharvest-field) 3.0)
		(= (in-storage depot2 brand4) 0.0)
		(at-location truck2 depot2)
		(= (service-time crane3) 10.0)
		(= (has-resource sugar-cane mill1) 3.0)
		(change-process brand3 brand2)
		(connected depot2 depot3)
		(change-process brand3 brand1)
		(= (in-storage depot3 brand4) 0.0)
		(change-process brand1 brand3)
		(connected depot1 depot2)
	)
	(:goal
			(and
				(>= (in-storage depot1 brand3) 3.0)
			)
	)
)