(define (problem delivery-x-4)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(= (weight item1) 1.0)
		(door rooma roomb)
		(door roomc rooma)
		(at item10 rooma)
		(= (weight item9) 2.0)
		(= (load_limit bot2) 4.0)
		(mount left1 bot1)
		(free left1)
		(= (load_limit bot1) 4.0)
		(= (current_load bot2) 0.0)
		(at item3 rooma)
		(door roomb roomd)
		(door rooma roomc)
		(at item5 rooma)
		(at item1 rooma)
		(= (weight item7) 1.0)
		(= (cost) 0.0)
		(at-bot bot2 rooma)
		(= (weight item10) 2.0)
		(mount right1 bot1)
	)
	(:goal
			(and
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomd)
				(at item7 roomd)
				(at item6 roomd)
				(at item5 roomd)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)