(define (problem delivery-x-4)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(at item5 rooma)
		(= (weight item6) 1.0)
		(at-bot bot2 rooma)
		(at item6 rooma)
		(mount right2 bot2)
		(at item7 rooma)
		(at item3 rooma)
		(= (load_limit bot1) 4.0)
		(at-bot bot1 rooma)
		(door rooma roomb)
		(door roomb rooma)
		(= (weight item2) 1.0)
		(at item10 rooma)
		(= (cost) 0.0)
		(= (current_load bot2) 0.0)
		(= (weight item9) 2.0)
		(at item8 rooma)
		(mount right1 bot1)
		(= (weight item4) 1.0)
		(free left1)
	)
	(:goal
			(and
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomd)
				(at item7 roomd)
				(at item6 roomd)
				(at item5 roomd)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)