(define (problem delivery-x-4)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(door rooma roomb)
		(at-bot bot1 rooma)
		(at item9 rooma)
		(at item8 rooma)
		(at item6 rooma)
		(= (weight item8) 1.0)
		(free left2)
		(= (weight item4) 1.0)
		(= (weight item2) 1.0)
		(free left1)
		(= (weight item6) 1.0)
		(at item10 rooma)
		(= (load_limit bot1) 4.0)
		(at-bot bot2 rooma)
		(= (weight item3) 1.0)
		(= (load_limit bot2) 4.0)
		(mount right2 bot2)
		(free right2)
		(door roomd roomb)
		(= (current_load bot1) 0.0)
		(at item2 rooma)
		(at item4 rooma)
		(free right1)
		(at item3 rooma)
		(mount left1 bot1)
		(at item5 rooma)
		(mount left2 bot2)
		(= (cost) 0.0)
		(= (current_load bot2) 0.0)
		(at item1 rooma)
	)
	(:goal
			(and
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomd)
				(at item7 roomd)
				(at item6 roomd)
				(at item5 roomd)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)