(define (problem delivery-x-4)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(at item4 rooma)
		(door roomd roomb)
		(door roomb rooma)
		(door rooma roomc)
		(= (weight item7) 1.0)
		(at item8 rooma)
		(at item2 rooma)
		(at item9 rooma)
		(= (load_limit bot1) 4.0)
		(mount right1 bot1)
		(at-bot bot1 rooma)
		(at item3 rooma)
		(mount left1 bot1)
		(= (weight item1) 1.0)
		(= (current_load bot1) 0.0)
		(at item6 rooma)
		(= (weight item9) 2.0)
		(= (weight item8) 1.0)
		(= (load_limit bot2) 4.0)
		(free right1)
		(= (weight item10) 2.0)
		(= (current_load bot2) 0.0)
		(= (weight item6) 1.0)
		(free right2)
		(mount right2 bot2)
		(free left1)
		(at item1 rooma)
		(= (weight item4) 1.0)
		(= (cost) 0.0)
		(door rooma roomb)
	)
	(:goal
			(and
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomd)
				(at item7 roomd)
				(at item6 roomd)
				(at item5 roomd)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)