(define (problem mprime-x-5)
	(:domain mystery-prime-typed)
	(:objects
		broccoli chocolate turkey tuna sweetroll shrimp cherry scallop - food
		satisfaction excitement intoxication lubricity - pleasure
		sciatica anxiety grief boils depression abrasion prostatitis angina jealousy laceration anger grief-2 dread loneliness hangover - pain
	)
	(:init
		(craves dread scallop)
		(eats cherry shrimp)
		(craves intoxication tuna)
		(eats chocolate broccoli)
		(= (locale shrimp) 1.0)
		(craves hangover scallop)
		(craves grief broccoli)
		(eats scallop cherry)
		(craves abrasion turkey)
		(craves prostatitis turkey)
		(= (harmony intoxication) 2.0)
		(eats turkey chocolate)
		(eats tuna turkey)
		(= (locale broccoli) 3.0)
		(eats sweetroll scallop)
		(= (locale scallop) 0.0)
		(= (harmony excitement) 3.0)
		(= (locale sweetroll) 0.0)
		(craves boils broccoli)
		(craves lubricity sweetroll)
		(craves anger cherry)
		(craves angina shrimp)
		(eats shrimp sweetroll)
		(eats tuna broccoli)
	)
	(:goal
			(and
				(craves loneliness shrimp)
				(craves grief shrimp)
			)
	)
)