(define (problem mprime-x-5)
	(:domain mystery-prime-typed)
	(:objects
		broccoli chocolate turkey tuna sweetroll shrimp cherry scallop - food
		satisfaction excitement intoxication lubricity - pleasure
		sciatica anxiety grief boils depression abrasion prostatitis angina jealousy laceration anger grief-2 dread loneliness hangover - pain
	)
	(:init
		(= (locale scallop) 0.0)
		(craves jealousy shrimp)
		(eats turkey chocolate)
		(craves prostatitis turkey)
		(craves lubricity sweetroll)
		(= (locale cherry) 1.0)
		(= (harmony satisfaction) 2.0)
		(craves loneliness scallop)
		(craves abrasion turkey)
		(craves laceration shrimp)
		(eats shrimp cherry)
		(eats turkey tuna)
		(eats sweetroll scallop)
		(= (locale turkey) 1.0)
		(eats scallop sweetroll)
		(eats chocolate shrimp)
		(= (harmony intoxication) 2.0)
		(craves depression turkey)
		(= (locale broccoli) 3.0)
		(craves sciatica broccoli)
		(craves angina shrimp)
		(eats shrimp sweetroll)
		(= (locale tuna) 3.0)
		(craves boils broccoli)
	)
	(:goal
			(and
				(craves loneliness shrimp)
				(craves grief shrimp)
			)
	)
)