(define (problem mprime-x-5)
	(:domain mystery-prime-typed)
	(:objects
		broccoli chocolate turkey tuna sweetroll shrimp cherry scallop - food
		satisfaction excitement intoxication lubricity - pleasure
		sciatica anxiety grief boils depression abrasion prostatitis angina jealousy laceration anger grief-2 dread loneliness hangover - pain
	)
	(:init
		(= (harmony excitement) 3.0)
		(= (harmony lubricity) 2.0)
		(craves hangover scallop)
		(eats turkey chocolate)
		(craves lubricity sweetroll)
		(eats turkey tuna)
		(craves excitement turkey)
		(= (harmony intoxication) 2.0)
		(eats scallop sweetroll)
		(craves dread scallop)
		(= (locale shrimp) 1.0)
		(= (locale turkey) 1.0)
		(craves grief-2 scallop)
		(craves boils broccoli)
		(eats cherry scallop)
		(eats tuna turkey)
		(craves sciatica broccoli)
		(eats chocolate turkey)
		(eats broccoli chocolate)
		(craves grief broccoli)
		(eats shrimp cherry)
		(eats sweetroll shrimp)
		(craves abrasion turkey)
		(craves angina shrimp)
		(craves depression turkey)
		(= (harmony satisfaction) 2.0)
		(craves satisfaction broccoli)
		(eats shrimp sweetroll)
		(eats cherry shrimp)
		(eats shrimp chocolate)
		(craves loneliness scallop)
		(eats scallop cherry)
		(craves laceration shrimp)
		(craves anxiety broccoli)
		(= (locale broccoli) 3.0)
		(craves intoxication tuna)
	)
	(:goal
			(and
				(craves loneliness shrimp)
				(craves grief shrimp)
			)
	)
)