(define (problem delivery-x-5)
	(:domain delivery)
	(:objects
		rooma roomb roomc - room
		item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(door rooma roomb)
		(mount left2 bot2)
		(free right2)
		(at item1 rooma)
		(= (weight item4) 1.0)
		(at item3 rooma)
		(= (weight item9) 1.0)
		(at item9 rooma)
		(door roomb rooma)
		(= (cost) 0.0)
		(at-bot bot1 rooma)
		(mount right2 bot2)
		(at item7 rooma)
		(= (weight item7) 1.0)
		(= (weight item10) 1.0)
		(free left1)
		(at item6 rooma)
		(= (weight item1) 1.0)
		(mount right1 bot1)
		(free right1)
		(mount left1 bot1)
	)
	(:goal
			(and
				(at item12 roomb)
				(at item11 roomb)
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomb)
				(at item7 roomb)
				(at item6 roomc)
				(at item5 roomc)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)