(define (problem delivery-x-5)
	(:domain delivery)
	(:objects
		rooma roomb roomc - room
		item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(= (weight item2) 1.0)
		(= (weight item8) 1.0)
		(= (cost) 0.0)
		(mount right1 bot1)
		(at item5 rooma)
		(at item8 rooma)
		(= (current_load bot1) 0.0)
		(= (current_load bot2) 0.0)
		(at item4 rooma)
		(free right1)
		(at item10 rooma)
		(= (weight item7) 1.0)
		(= (weight item10) 1.0)
		(at item2 rooma)
		(= (weight item11) 2.0)
		(door roomb rooma)
		(= (load_limit bot2) 4.0)
		(at item9 rooma)
		(free left2)
		(= (weight item3) 1.0)
		(at item12 rooma)
		(mount right2 bot2)
		(= (load_limit bot1) 4.0)
		(at item1 rooma)
		(at item7 rooma)
		(at item6 rooma)
		(at item11 rooma)
		(= (weight item4) 1.0)
		(= (weight item5) 2.0)
		(at item3 rooma)
		(mount left1 bot1)
		(= (weight item12) 2.0)
	)
	(:goal
			(and
				(at item12 roomb)
				(at item11 roomb)
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomb)
				(at item7 roomb)
				(at item6 roomc)
				(at item5 roomc)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)