(define (problem delivery-x-5)
	(:domain delivery)
	(:objects
		rooma roomb roomc - room
		item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(= (weight item8) 1.0)
		(at item10 rooma)
		(at item7 rooma)
		(mount left1 bot1)
		(at item11 rooma)
		(= (weight item7) 1.0)
		(= (current_load bot1) 0.0)
		(at-bot bot2 rooma)
		(door roomc rooma)
		(at item5 rooma)
		(= (weight item1) 1.0)
		(= (weight item10) 1.0)
		(at item12 rooma)
		(free right1)
		(at item6 rooma)
		(= (cost) 0.0)
		(at item8 rooma)
		(= (load_limit bot2) 4.0)
		(at item1 rooma)
		(= (weight item3) 1.0)
		(door roomb rooma)
		(mount right1 bot1)
		(free left1)
		(= (current_load bot2) 0.0)
		(at item9 rooma)
		(= (weight item5) 2.0)
		(at-bot bot1 rooma)
		(at item2 rooma)
		(= (weight item4) 1.0)
		(door rooma roomc)
		(= (weight item2) 1.0)
		(= (load_limit bot1) 4.0)
	)
	(:goal
			(and
				(at item12 roomb)
				(at item11 roomb)
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomb)
				(at item7 roomb)
				(at item6 roomc)
				(at item5 roomc)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)