(define (problem prob1)
	(:domain supply-chain)
	(:objects
		brand1 brand2 brand3 brand4 - brand
		sugar-cane - raw-cane
		truck1 truck2 - truck
		depot1 depot2 depot3 - depot
		mill1 mill2 mill3 - mill
		crane1 crane2 crane3 - crane
	)
	(:init
		(= (in-storage depot3 brand2) 0.0)
		(= (service-time crane2) 15.0)
		(= (service-time crane1) 10.0)
		(= (max-changing mill2) 2.0)
		(change-process brand3 brand4)
		(= (in-storage depot3 brand1) 0.0)
		(change-process brand4 brand3)
		(= (cost-process mill1) 1.0)
		(produce mill2 brand3)
		(= (in-storage mill3 brand1) 0.0)
		(= (mill-cost) 0.0)
		(connected mill2 depot1)
		(= (max-service-time crane3) 10.0)
		(= (inventory-cost) 0.0)
		(change-process brand2 brand1)
		(current-process mill3 brand2)
		(= (in-truck-sugar brand2 truck1) 0.0)
		(= (in-storage mill3 brand2) 0.0)
		(connected mill1 depot2)
		(available mill3)
		(= (has-resource sugar-cane mill2) 10.0)
		(= (capacity crane1) 5.0)
		(available mill1)
		(current-process mill1 brand1)
		(= (has-resource sugar-cane mill1) 10.0)
		(= (max-service-time crane1) 10.0)
		(connected depot2 mill2)
		(at-location truck2 depot2)
		(produce mill3 brand1)
		(at-location truck1 depot1)
		(change-process brand2 brand4)
		(= (max-produce mill1) 5.0)
		(produce mill1 brand3)
		(= (handling-cost) 0.0)
		(connected depot3 depot2)
		(= (in-storage depot1 brand3) 0.0)
		(= (truck-cap truck1) 10.0)
		(produce mill1 brand4)
		(= (in-storage depot2 brand2) 0.0)
		(= (in-storage mill2 brand1) 0.0)
		(= (in-storage depot3 brand4) 0.0)
		(change-process brand4 brand1)
		(= (capacity crane2) 5.0)
		(connected depot1 depot2)
		(= (in-truck-sugar brand4 truck1) 0.0)
		(= (in-storage depot1 brand2) 0.0)
		(= (in-truck-sugar brand4 truck2) 0.0)
		(connected depot2 mill1)
		(= (in-truck-sugar brand1 truck1) 0.0)
		(change-process brand1 brand3)
		(connected mill2 mill1)
		(produce mill3 brand4)
		(connected depot3 mill2)
	)
	(:goal
			(and
				(>= (in-storage depot1 brand1) 10.0)
				(>= (in-storage depot2 brand3) 5.0)
			)
	)
)