(define (problem prob_10)
(:domain bottles-all)
	(:objects
		 l1 l2 l3 l4 l5 - bottleleft
		 r1 r2 r3 r4 r5 - bottleright
	)
	(:init
		(= (on-platform) 0)
		(= (litres l1) 6)
		(= (litres l2) 10)
		(= (litres l3) 5)
		(= (litres l4) 4)
		(= (litres l5) 5)
		(= (litres r1) 0)
		(= (litres r2) 0)
		(= (litres r3) 0)
		(= (litres r4) 0)
		(= (litres r5) 0)
		(capped l1)
		(capped l2)
		(capped l3)
		(capped l4)
		(capped l5)
		(capped r1)
		(capped r2)
		(capped r3)
		(capped r4)
		(capped r5)
	)
	(:goal
		(and
			(= (litres r1) 2)
			(= (litres r2) 16)
			(= (litres r3) 5)
			(= (litres r4) 3)
			(= (litres r5) 4)
			(packed l1)
			(packed l2)
			(packed l3)
			(packed l4)
			(packed l5)
			(packed r1)
			(packed r2)
			(packed r3)
			(packed r4)
			(packed r5)
		)
	)
)