(define (problem prob_12)
(:domain bottles-all)
	(:objects
		 l1 l2 l3 l4 l5 l6 - bottleleft
		 r1 r2 r3 r4 r5 r6 - bottleright
	)
	(:init
		(= (on-platform) 0)
		(= (litres l1) 2)
		(= (litres l2) 2)
		(= (litres l3) 18)
		(= (litres l4) 6)
		(= (litres l5) 4)
		(= (litres l6) 4)
		(= (litres r1) 0)
		(= (litres r2) 0)
		(= (litres r3) 0)
		(= (litres r4) 0)
		(= (litres r5) 0)
		(= (litres r6) 0)
		(capped l1)
		(capped l2)
		(capped l3)
		(capped l4)
		(capped l5)
		(capped l6)
		(capped r1)
		(capped r2)
		(capped r3)
		(capped r4)
		(capped r5)
		(capped r6)
	)
	(:goal
		(and
			(= (litres r1) 2)
			(= (litres r2) 20)
			(= (litres r3) 4)
			(= (litres r4) 6)
			(= (litres r5) 2)
			(= (litres r6) 2)
			(packed l1)
			(packed l2)
			(packed l3)
			(packed l4)
			(packed l5)
			(packed l6)
			(packed r1)
			(packed r2)
			(packed r3)
			(packed r4)
			(packed r5)
			(packed r6)
		)
	)
)