(define (problem prob_16)
(:domain bottles-all)
	(:objects
		 l1 l2 l3 l4 l5 l6 l7 l8 - bottleleft
		 r1 r2 r3 r4 r5 r6 r7 r8 - bottleright
	)
	(:init
		(= (on-platform) 0)
		(= (litres l1) 6)
		(= (litres l2) 17)
		(= (litres l3) 6)
		(= (litres l4) 6)
		(= (litres l5) 3)
		(= (litres l6) 3)
		(= (litres l7) 4)
		(= (litres l8) 3)
		(= (litres r1) 0)
		(= (litres r2) 0)
		(= (litres r3) 0)
		(= (litres r4) 0)
		(= (litres r5) 0)
		(= (litres r6) 0)
		(= (litres r7) 0)
		(= (litres r8) 0)
		(capped l1)
		(capped l2)
		(capped l3)
		(capped l4)
		(capped l5)
		(capped l6)
		(capped l7)
		(capped l8)
		(capped r1)
		(capped r2)
		(capped r3)
		(capped r4)
		(capped r5)
		(capped r6)
		(capped r7)
		(capped r8)
	)
	(:goal
		(and
			(= (litres r1) 4)
			(= (litres r2) 1)
			(= (litres r3) 3)
			(= (litres r4) 27)
			(= (litres r5) 5)
			(= (litres r6) 1)
			(= (litres r7) 6)
			(= (litres r8) 1)
			(packed l1)
			(packed l2)
			(packed l3)
			(packed l4)
			(packed l5)
			(packed l6)
			(packed l7)
			(packed l8)
			(packed r1)
			(packed r2)
			(packed r3)
			(packed r4)
			(packed r5)
			(packed r6)
			(packed r7)
			(packed r8)
		)
	)
)