(define (problem prob_8)
(:domain bottles-all)
	(:objects
		 l1 l2 l3 l4 - bottleleft
		 r1 r2 r3 r4 - bottleright
	)
	(:init
		(= (on-platform) 0)
		(= (litres l1) 4)
		(= (litres l2) 6)
		(= (litres l3) 9)
		(= (litres l4) 5)
		(= (litres r1) 0)
		(= (litres r2) 0)
		(= (litres r3) 0)
		(= (litres r4) 0)
		(capped l1)
		(capped l2)
		(capped l3)
		(capped l4)
		(capped r1)
		(capped r2)
		(capped r3)
		(capped r4)
	)
	(:goal
		(and
			(= (litres r1) 2)
			(= (litres r2) 13)
			(= (litres r3) 3)
			(= (litres r4) 6)
			(packed l1)
			(packed l2)
			(packed l3)
			(packed l4)
			(packed r1)
			(packed r2)
			(packed r3)
			(packed r4)
		)
	)
)