(define (problem delivery-x-3)
	(:domain delivery)
	(:objects
		rooma roomb roomc - room
		item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(= (weight item5) 1.0)
		(at-bot bot1 rooma)
		(= (load_limit bot2) 4.0)
		(at item8 rooma)
		(mount left1 bot1)
		(at-bot bot2 rooma)
		(= (weight item4) 2.0)
		(door rooma roomc)
		(mount right2 bot2)
		(free left2)
		(= (weight item7) 2.0)
		(= (weight item8) 2.0)
		(= (load_limit bot1) 4.0)
		(= (cost) 0.0)
		(door roomc rooma)
		(free left1)
		(mount left2 bot2)
		(= (current_load bot2) 0.0)
		(at item6 rooma)
		(= (current_load bot1) 0.0)
		(free right2)
		(at item1 rooma)
		(= (weight item3) 2.0)
		(at item4 rooma)
		(door rooma roomb)
		(at item7 rooma)
	)
	(:goal
			(and
				(at item8 roomb)
				(at item7 roomb)
				(at item6 roomb)
				(at item5 roomb)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)