(define (problem mprime-x-9)
	(:domain mystery-prime-typed)
	(:objects
		apple flounder haroset hamburger wurst hotdog guava - food
		entertainment intoxication curiosity excitement - pleasure
		dread sciatica abrasion prostatitis loneliness anger hangover anxiety laceration boils jealousy angina grief - pain
	)
	(:init
		(= (harmony excitement) 1.0)
		(= (harmony entertainment) 3.0)
		(eats flounder hamburger)
		(eats apple hotdog)
		(eats guava apple)
		(= (locale hotdog) 1.0)
		(= (locale guava) 4.0)
		(= (locale flounder) 2.0)
		(craves boils guava)
		(craves prostatitis haroset)
		(craves dread flounder)
		(craves loneliness haroset)
		(craves grief guava)
		(craves jealousy guava)
		(= (locale hamburger) 0.0)
		(craves hangover haroset)
		(= (harmony curiosity) 1.0)
		(eats hamburger flounder)
		(eats wurst hotdog)
		(craves laceration wurst)
		(craves anger haroset)
		(eats guava haroset)
		(craves intoxication haroset)
		(eats hotdog wurst)
		(craves angina guava)
		(eats hotdog apple)
		(eats haroset hamburger)
		(eats flounder wurst)
		(= (locale haroset) 2.0)
		(craves excitement guava)
		(craves abrasion haroset)
	)
	(:goal
			(and
				(craves sciatica hamburger)
				(craves jealousy wurst)
			)
	)
)