(define (problem mprime-x-4)
	(:domain mystery-prime-typed)
	(:objects
		muffin ham scallion shrimp cherry grapefruit bacon arugula scallop wurst - food
		aesthetics - pleasure
		hangover dread sciatica jealousy loneliness abrasion anger - pain
	)
	(:init
		(eats arugula scallop)
		(eats cherry muffin)
		(= (locale bacon) 1.0)
		(= (locale arugula) 4.0)
		(eats wurst bacon)
		(eats arugula wurst)
		(= (locale scallop) 3.0)
		(eats ham muffin)
		(= (locale shrimp) 2.0)
		(craves hangover muffin)
		(craves jealousy bacon)
		(eats cherry ham)
		(= (locale muffin) 4.0)
		(eats shrimp scallion)
		(= (locale grapefruit) 0.0)
		(eats wurst grapefruit)
		(eats bacon wurst)
		(eats scallion shrimp)
		(eats arugula cherry)
		(= (locale cherry) 4.0)
		(eats grapefruit wurst)
		(= (locale scallion) 1.0)
		(craves abrasion scallop)
		(eats arugula bacon)
		(eats muffin arugula)
		(eats grapefruit scallop)
		(eats cherry arugula)
		(eats wurst arugula)
		(eats cherry shrimp)
		(eats shrimp cherry)
		(eats arugula muffin)
		(eats scallop grapefruit)
		(eats muffin cherry)
		(craves loneliness arugula)
		(eats muffin scallion)
	)
	(:goal
			(and
				(craves sciatica wurst)
			)
	)
)