(define (problem mprime-x-4)
	(:domain mystery-prime-typed)
	(:objects
		muffin ham scallion shrimp cherry grapefruit bacon arugula scallop wurst - food
		aesthetics - pleasure
		hangover dread sciatica jealousy loneliness abrasion anger - pain
	)
	(:init
		(eats scallion muffin)
		(eats cherry ham)
		(craves sciatica grapefruit)
		(craves loneliness arugula)
		(eats scallop grapefruit)
		(eats ham cherry)
		(eats cherry shrimp)
		(craves jealousy bacon)
		(= (locale cherry) 4.0)
		(eats wurst grapefruit)
		(= (locale bacon) 1.0)
		(eats muffin arugula)
		(eats arugula wurst)
		(eats grapefruit scallop)
		(craves anger wurst)
		(eats arugula muffin)
		(eats scallion shrimp)
		(eats scallop arugula)
		(= (locale shrimp) 2.0)
		(eats muffin scallion)
		(= (locale ham) 2.0)
		(eats ham muffin)
		(craves abrasion scallop)
		(eats arugula cherry)
		(= (locale arugula) 4.0)
		(= (locale grapefruit) 0.0)
		(= (locale wurst) 0.0)
		(= (locale scallop) 3.0)
		(eats bacon arugula)
		(craves hangover muffin)
		(eats grapefruit wurst)
		(eats cherry muffin)
		(eats muffin cherry)
		(eats muffin ham)
		(= (locale scallion) 1.0)
	)
	(:goal
			(and
				(craves sciatica wurst)
			)
	)
)