(define (problem mprime-x-4)
	(:domain mystery-prime-typed)
	(:objects
		muffin ham scallion shrimp cherry grapefruit bacon arugula scallop wurst - food
		aesthetics - pleasure
		hangover dread sciatica jealousy loneliness abrasion anger - pain
	)
	(:init
		(eats cherry arugula)
		(= (locale ham) 2.0)
		(eats ham cherry)
		(eats wurst grapefruit)
		(eats scallop grapefruit)
		(eats cherry muffin)
		(eats scallion shrimp)
		(craves anger wurst)
		(eats grapefruit scallop)
		(eats arugula cherry)
		(craves jealousy bacon)
		(eats arugula scallop)
		(craves sciatica grapefruit)
		(eats muffin ham)
		(= (locale muffin) 4.0)
		(eats shrimp cherry)
		(eats shrimp scallion)
		(eats ham muffin)
		(craves dread ham)
		(eats arugula muffin)
		(= (locale scallop) 3.0)
		(= (locale wurst) 0.0)
		(= (locale cherry) 4.0)
		(= (locale shrimp) 2.0)
		(eats wurst bacon)
		(= (harmony aesthetics) 1.0)
		(craves abrasion scallop)
		(eats scallion muffin)
		(craves loneliness arugula)
		(eats cherry shrimp)
		(eats muffin arugula)
		(eats scallop arugula)
		(= (locale arugula) 4.0)
		(craves aesthetics shrimp)
		(eats muffin scallion)
	)
	(:goal
			(and
				(craves sciatica wurst)
			)
	)
)